solution 17/07
VadimKadasiev/Book_Store_Project pull request #5
Opened 2024-07-17 20:31 UTC by VadimKadasiev

2024-07-18 14:28 UTC, MentorMateAcademy requested changes

2024-07-18 14:28 UTC, MentorMateAcademy commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Add these to constant

2024-07-19 07:59 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-19 07:59 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2024-07-19 07:59 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/UserLoginRequestDto.java
> +        @NotEmpty
same

2024-07-19 07:59 UTC, Elena-Bruyako commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(HEADER_TYPE);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-07-19 07:59 UTC, Elena-Bruyako commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +    private static final String HEADER_TYPE = "Authorization";
```suggestion
```

2024-07-19 07:59 UTC, Elena-Bruyako commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(TOKEN_TYPE.length());
```

2024-07-20 11:40 UTC, Elena-Bruyako approved these changes
well done

2024-07-20 15:14 UTC, merged