solution 21/07
VadimKadasiev/Book_Store_Project pull request #6
Opened 2024-07-21 15:32 UTC by VadimKadasiev

2024-07-23 09:47 UTC, Elena-Bruyako requested changes
Let's improve your implementation

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/CategoryController.java
> +@RequestMapping(value = "/categories")
```suggestion
@RequestMapping("/categories")
```

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/CreateBookRequestDto.java
> +    @NotNull(message = "CategoryIds field can't be empty")
```suggestion
    @NotEmpty(message = "CategoryIds field can't be empty")
```

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/CreateBookRequestDto.java
>      private String coverImage;
Also, use `@NotBlank` for String

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/mapper/BookMapper.java
> +        bookDto.setCategoryIds(book.getCategories().stream().map(Category::getId).toList());
```suggestion
        bookDto.setCategoryIds(book.getCategories()
        .stream()
        .map(Category::getId)
        .toList());
```

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/model/Category.java
> +    @Column(nullable = false, unique = true)
```suggestion
    @Column(nullable = false)
```

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/repository/CategoryRepository.java
> +
```suggestion
```

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/CategoryServiceImpl.java
> +        return categoryRepository.findAll(pageable).stream().map(categoryMapper::toDto).toList();
```suggestion
        return categoryRepository.findAll(pageable)
        .stream()
        .map(categoryMapper::toDto)
        .toList();
```

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(categoryRepository.findById(id).get());
add .orElseThrow(()

2024-07-23 09:47 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/CategoryServiceImpl.java
> +        Category category = categoryMapper.toModel(categoryDto);
First, find Category by id
Second, use MapStruct to update `mapper.updateCategoryFromDto(categoryDto, category);`

2024-07-24 17:45 UTC, okuzan requested changes

2024-07-24 17:45 UTC, okuzan commented on src/main/java/book/store/service/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Can't find category with ID " + id));
please use EntityNotFoundException for such cases. Avoid overusing generic exceptions like runtime exception

2024-07-24 17:47 UTC, okuzan requested changes

2024-07-24 17:47 UTC, okuzan commented on src/main/java/book/store/model/Category.java
> +@SQLRestriction(value = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE categories SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-07-24 17:47 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/08-create-books-categories-table.yaml
```suggestion
      file: db/changelog/changes/08-create-books-categories-table.yaml

```

2024-07-26 06:56 UTC, Elena-Bruyako requested changes
see comment

2024-07-26 06:56 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid CategoryDto categoryDto) {
Why do you provide dto with Id in request to createCategory endpoint?

2024-07-27 12:15 UTC, okuzan approved these changes

2024-07-28 04:34 UTC, merged