solution 18/08
VadimKadasiev/Book_Store_Project pull request #9
Opened 2024-08-18 16:01 UTC by VadimKadasiev

2024-08-20 21:02 UTC, sarakhmen requested changes
let's slightly improve your solution :)

2024-08-20 21:02 UTC, sarakhmen commented on src/main/java/book/store/controller/OrderController.java
> +    public List<OrderResponseDto> getOrders(Authentication authentication, Pageable pageable) {
please add default pagable params. fix in all places

2024-08-20 21:02 UTC, sarakhmen commented on src/main/java/book/store/controller/OrderController.java
> +                .substring(15);
why did you modify status value here? it should be passed in a correct format

2024-08-20 21:02 UTC, sarakhmen commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +    public List<OrderResponseDto> getOrders(User user, Pageable pageable) {
add @override in all places where needed

2024-08-20 21:02 UTC, sarakhmen commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +    public void changeOrderStatus(Long orderId, Order.OrderStatus orderStatus) {
add transactional

2024-08-22 13:37 UTC, Elena-Bruyako requested changes
see comments

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/OrderController.java
> +                                        @RequestBody OrderRequestDto orderRequestDto) {
```suggestion
                                        @RequestBody @Valid OrderRequestDto orderRequestDto) {
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/model/Order.java
> +    private LocalDateTime orderDate;
```suggestion
    private LocalDateTime orderDate = LocalDateTime.now();
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/model/Order.java
> +    @JoinColumn(nullable = false)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/model/Order.java
> +    @JoinColumn(name = "order_id")
```suggestion
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/model/Order.java
> +    private Set<OrderItem> orderItems;
```suggestion
    private Set<OrderItem> orderItems;
    
    @Column(nullable = false)
    private boolean isDeleted;
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/model/OrderItem.java
> +    @JoinColumn(nullable = false)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +    @Transactional
Transactional won't work here

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +    public void createOrderItems(User user, Order order) {
```suggestion
    private void createOrderItems(User user, Order order) {
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +                        + orderItemId + " in order by ID " + orderId)));
```suggestion
        OrderItem item = orderItemRepository.findByIdAndOrderIdAndUserId(orderItemId, orderId, userId)
                .orElseThrow(() -> new EntityNotFoundException(
                        .....
                ));
        return orderItemMapper.toOrderItemDto(item);
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +                .map(orderItemMapper::toOrderItemResponseDto).collect(Collectors.toSet());
```suggestion
        Order order = orderRepository.findByIdAndUserId(orderId, userId)
                .orElseThrow(() -> new EntityNotFoundException(
                        .....
                ));
        return orderItemMapper.toOrderItemDtoList(order.getOrderItems());
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +                orderMapper::orderToOrderResponseDto).toList();
```suggestion
        return orderRepository.findAllByUserId(user.getId())
        .stream()
        .map(orderMapper::orderToOrderResponseDto)
        .toList();
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +    private void checkUserOrderMatching(User user, Long orderId) {
remove

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findById(orderId).orElseThrow();
```suggestion
        Order order = orderRepository.findById(orderId).orElseThrow(() -> new EntityNotFoundException(....
```

2024-08-22 13:37 UTC, Elena-Bruyako commented on src/main/java/book/store/service/impl/OrderServiceImpl.java
> +        }
```suggestion
        ShoppingCart cart = shoppingCartRepository.findByUserId(userId);
        if (cart.getCartItems().isEmpty()) {
            throw new OrderProcessingException("Cart is empty for user: " + userId);
        }
```

2024-08-23 07:50 UTC, Elena-Bruyako approved these changes

2024-08-28 21:03 UTC, merged